import styled from '@emotion/styled'
import { Header } from 'components/Header'
import { Recommended } from 'components/Recommended'
import { SearchBar } from 'components/SearchBar'
import { TimeDeal } from 'components/TimeDeal'
import { TopBanner } from 'components/TopBanner'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Answer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ScrollContainer>
          <Header />
          <SearchBar />
          <TopBanner />
          <TimeDeal />
          <Recommended />
        </ScrollContainer>
      </Container>
    </>
  )
}

const Container = styled.div({
  position: 'absolute',
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  background: '#000000',
  display: 'flex',
  justifyContent: 'center'
})

const ScrollContainer = styled.div({
  display: 'flex',
  flexDirection: 'column',
  width: 360,
  height: '100%',
  overflowY: 'auto',
  background: '#F7FAFC'
})